# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cc6ce47640f5b95d8ce901ab63c29e2e64e1f7d0b4bf646bfbad505774648fecba91c8d3fe66009b45b495d580394ba9f96adefaf45f68de82cde8352c14c09
  instagram_client_id: 910380fe0780405f9d51ababaf69dd32
  instagram_client_secret: 372e8e4eea29468cbc533b3e389dcc66
  instagram_redirect_uri: 'http://localhost:3000/oauth/signin'

test:
  secret_key_base: e0fc4c17e2ea6c1cbd62f383df87db8e9eb3c07578ea4015a38c1f486524ea4a75aea652fb67c54a406bb7e8a033b3ed990217800fd72676566c25e07663699c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  instagram_client_id: 3f4a3d527de348519b64caecc611a6c7
  instagram_client_secret: 7134b32f9e484a2ca508719a5284fa88
  instagram_redirect_uri: 'http://instaspy.herokuapp.com/oauth/signin'
